name: pandas-checks

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        config:
          # - { os: ubuntu-latest, python-version: '3.9', pandas-version: '1.5.0' }
          - { os: ubuntu-latest, python-version: '3.9', pandas-version: '2.2.0' }
          - { os: ubuntu-latest, python-version: '3.9', pandas-version: 'latest' }

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.python-version }}) - pandas ${{ matrix.config.pandas-version }}

    steps:
      - name: Set up Python Version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install package
        run: |
          poetry install
          if [ "${{ matrix.config.pandas-version }}" == "latest" ]; then
            poetry add pandas@latest
          else
            poetry add pandas==${{ matrix.config.pandas-version }}
          fi
      
      - run: |
          source $VENV
          pytest --version

      - name: Test with pytest
        run: poetry run pytest tests/ --verbose